name: "Deploy to Nuget"

on:
    push:
        branches:
        - "master"
    pull_request:
        branches:
        - "master"

jobs:
    deploy:
        name: 'Deploy'
        runs-on: 'ubuntu-latest'
        timeout-minutes: 15

        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run: dotnet build --configuration Release
        - uses: "bwdev/Repositorio@latest"