name: Publish Repositorio

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Publish Repositorio
      run: dotnet build -c Release
    
    - name: Generate Nuget package
      run: dotnet pack --no-build -c Release -o .
      
    - name: Push to Nuget
      run: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      
      #with:
      #  PROJECT_FILE_PATH: Repositorio/Repositorio.csproj
      #  NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      #  VERSION_FILE_PATH: Repositorio/Directory.Build.Props
