name: Publish Repositorio.Infrastructure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish Infrastructure
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: Repositorio.Infrastructure/Repositorio.Infrastructure.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        VERSION_FILE_PATH: Repositorio.Infrastructure/Directory.Build.Props
